---
abstract: 'Perl implementation of leaky bucket rate limiting'
author:
  - 'Marcus Slagle <marc.slagle@online-rewards.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-LeakyBucket
no_index:
  directory:
    - t
    - inc
requires:
  Cache::Memcached: 0
  Cache::Memcached::Fast: 0
version: 0.08
